version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:arm
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "443:443/tcp"
    cap_add:
      - NET_ADMIN
    environment:
      - ServerIP=10.0.0.3
      - DNS1='10.0.0.2#54'
      - DNS2=''
      - IPv6=false
      - TZ=CET
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=admin
    # Add your own custom hostnames you need for your domain
    extra_hosts:
      - 'loki.eniac.local:192.168.1.5'
    volumes:
      - "./config/pihole:/etc/pihole"
      - "./config/dnsmasq:/etc/dnsmasq.d"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 192.168.1.5

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
